"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Image from "next/image";
import { connectWallet, EXPLORER, getBounties, getBounty, getSummary, policyBoundToExecution, writeAndVerify, type TxPhase } from "@/lib/genlayer";
import type { Bounty, Summary } from "@/lib/types";

const phaseText:Record<TxPhase,string>={SIGN:"Confirm in wallet",SUBMITTED:"Transaction submitted",CONSENSUS:"Validators are reviewing",FINALIZED:"Finalized on Bradbury",READBACK:"Verifying canonical state",SUCCESS:"Canonical state verified",ERROR:"Transaction failed"};
const zero="0x0000000000000000000000000000000000000000";
const gen=(v:string)=>`${(Number(BigInt(v||"0"))/1e18).toFixed(2)} GEN`;

export default function Home(){
 const [account,setAccount]=useState("");const [items,setItems]=useState<Bounty[]>([]);const [summary,setSummary]=useState<Summary>({bounties:0,open:0,under_review:0,finalized:0,locked:"0"});const [selected,setSelected]=useState<Bounty|null>(null);const [phase,setPhase]=useState<TxPhase|null>(null);const [hash,setHash]=useState("");const [error,setError]=useState("");
 const refresh=useCallback(async()=>{try{const [b,s]=await Promise.all([getBounties(),getSummary()]);setItems(b);setSummary(s);if(selected)setSelected(b.find(x=>x.id===selected.id)||null);}catch(e){setError(e instanceof Error?e.message:"Contract read failed");}},[selected]);
 useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
 void refresh();},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const progress=(p:TxPhase,h?:string)=>{setPhase(p);if(h)setHash(h)};const run=async(fn:()=>Promise<unknown>)=>{setError("");try{await fn();await refresh()}catch(e){setError(e instanceof Error?e.message:"Transaction failed")}};
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!account)return setError("Connect wallet first");const f=new FormData(e.currentTarget),before=summary.bounties;await run(()=>writeAndVerify(account,"create_bounty",[f.get("title"),f.get("issue"),f.get("policy"),BigInt(f.get("bond") as string)*10n**18n],getSummary,s=>s.bounties===before+1,progress,BigInt(f.get("bounty") as string)*10n**18n));}
 async function mutate(b:Bounty,fn:string,args:unknown[],expected:(x:Bounty)=>boolean,value=0n){if(!account)return setError("Connect wallet first");await run(()=>writeAndVerify(account,fn,args,()=>getBounty(b.id),expected,progress,value));}
 const me=account.toLowerCase();const party=selected&&[selected.maintainer,selected.contributor,selected.challenger].map(x=>x.toLowerCase()).includes(me);
 return <main><nav><a href="#top" className="brand"><Image src="/patcharena-logo.png" width={38} height={38} alt="PatchArena logo" priority/> PATCHARENA</a><div><a href="#bounties">Bounties</a><a href="#protocol">Protocol</a></div><button onClick={async()=>{try{setAccount(await connectWallet())}catch(e){setError(e instanceof Error?e.message:"Wallet failed")}}}>{account?`${account.slice(0,6)}…${account.slice(-4)}`:"Connect wallet"}</button></nav>
 <section className="hero" id="top"><div><p className="eyebrow">OPEN-SOURCE BOUNTIES · DECIDED BY CONSENSUS</p><h1>Don&apos;t trust the patch.<br/><em>Prove it.</em></h1><p>Fund an issue, submit a fix, challenge weak evidence, and let GenLayer validators decide what is merge-ready.</p><a className="cta" href="#create">Post a bounty →</a></div><div className="terminal"><header><i/><i/><i/><span>CONSENSUS REVIEW</span></header><code><b>$</b> inspect issue policy<br/><b>$</b> fetch patch + test evidence<br/><b>$</b> test counterevidence<br/><strong>✓ VERDICT BOUND TO PAYOUT</strong></code><footer><span>POLICY FROZEN</span><span>LATEST REVISION</span><span>EXACTLY ONCE</span></footer></div></section>
 <section className="stats"><div><b>{summary.bounties}</b><span>BOUNTIES</span></div><div><b>{summary.open}</b><span>OPEN / PATCHED</span></div><div><b>{summary.under_review}</b><span>UNDER REVIEW</span></div><div><b>{gen(summary.locked)}</b><span>LOCKED VALUE</span></div></section>
 <section className="board" id="bounties"><div className="heading"><div><p className="eyebrow">CANONICAL BRADBURY STATE</p><h2>Patch board</h2></div><button className="quiet" onClick={()=>void refresh()}>Refresh ↻</button></div>{items.length===0?<div className="empty"><b>∅</b><h3>No bounties yet</h3><p>Create the first on-chain issue bounty. No sample records are fabricated.</p></div>:<div className="grid">{items.map(b=><button className="card" key={b.id} onClick={()=>setSelected(b)}><header><span>{b.status}</span><small>#{String(b.id).padStart(3,"0")}</small></header><h3>{b.title}</h3><p>{b.verdict||"Awaiting patch evidence"}</p><footer><b>{gen(b.amount)}</b><span>{b.payout_bps/100}% payout →</span></footer></button>)}</div>}</section>
 <section className="create" id="create"><div><p className="eyebrow">NEW BOUNTY</p><h2>Put value behind the issue.</h2><p>Use public HTTPS sources. The accepted issue and policy are frozen at first review, so an appeal cannot rewrite the rules.</p></div><form onSubmit={create}><label>Title<input name="title" required minLength={3} maxLength={120} placeholder="Fix signature replay in session refresh"/></label><label>Issue URL<input name="issue" type="url" required placeholder="https://github.com/org/repo/issues/123"/></label><label>Acceptance policy URL<input name="policy" type="url" required placeholder="https://github.com/org/repo/blob/main/SECURITY.md"/></label><div className="split"><label>Bounty (GEN)<input name="bounty" type="number" min="1" required/></label><label>Challenge bond (GEN)<input name="bond" type="number" min="1" required/></label></div><button className="cta">Fund and publish →</button></form></section>
 <section className="protocol" id="protocol"><p className="eyebrow">THE REVIEW PIPELINE</p><h2>Evidence in. Consequence out.</h2><div>{[["01","Fund","Maintainer locks bounty and challenge terms."],["02","Patch","Contributor links patch and reproducible tests."],["03","Challenge","Independent reviewer bonds counterevidence."],["04","Consensus","Validators inspect sources and freeze policy."],["05","Settle","Latest verdict controls bounded payout."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 {selected&&<div className="backdrop" onClick={()=>setSelected(null)}><article className="modal" role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()}><button className="x" aria-label="Close" onClick={()=>setSelected(null)}>×</button><p className="eyebrow">BOUNTY #{selected.id} · {selected.status}</p><h2>{selected.title}</h2><dl><div><dt>Bounty</dt><dd>{gen(selected.amount)}</dd></div><div><dt>Challenge bond</dt><dd>{gen(selected.challenge_bond)}</dd></div><div><dt>Verdict</dt><dd>{selected.verdict||"Pending"}</dd></div><div><dt>Contributor payout</dt><dd>{selected.payout_bps/100}%</dd></div></dl>
 {selected.status==="OPEN"&&me!==selected.maintainer.toLowerCase()&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(selected,"submit_patch",[selected.id,f.get("patch"),f.get("tests")],b=>b.status==="PATCHED")}}><input name="patch" type="url" required placeholder="Patch or pull request URL"/><input name="tests" type="url" required placeholder="Test/build evidence URL"/><button className="cta">Submit patch</button></form>}
 {selected.status==="PATCHED"&&me!==selected.maintainer.toLowerCase()&&me!==selected.contributor.toLowerCase()&&<form onSubmit={e=>{e.preventDefault();const url=new FormData(e.currentTarget).get("counter");void mutate(selected,"challenge_patch",[selected.id,url],b=>b.status==="CHALLENGED",BigInt(selected.challenge_bond))}}><input name="counter" type="url" required placeholder="Counterevidence URL"/><button className="outline">Challenge with {gen(selected.challenge_bond)}</button></form>}
 {selected.status==="OPEN"&&me===selected.maintainer.toLowerCase()&&<button className="outline full" onClick={()=>void mutate(selected,"cancel_open",[selected.id],b=>b.status==="FINALIZED")}>Cancel untouched bounty</button>}
 {["PATCHED","CHALLENGED"].includes(selected.status)&&<button className="cta full" onClick={()=>void mutate(selected,"review_patch",[selected.id],b=>b.status==="REVIEWED"&&policyBoundToExecution(b))}>Run consensus review</button>}
 {selected.status==="REVIEWED"&&party&&selected.verdict!=="REPAIR_REQUIRED"&&<form onSubmit={e=>{e.preventDefault();const url=new FormData(e.currentTarget).get("appeal");void mutate(selected,"appeal",[selected.id,url],b=>b.status==="APPEALED"&&policyBoundToExecution(b))}}><input name="appeal" type="url" required placeholder="New appeal evidence URL"/><button className="outline">Use one appeal</button></form>}
 {["REVIEWED","APPEALED"].includes(selected.status)&&party&&selected.verdict==="REPAIR_REQUIRED"&&<form onSubmit={e=>{e.preventDefault();const url=new FormData(e.currentTarget).get("repair");void mutate(selected,"repair_evidence",[selected.id,url],b=>b.status==="APPEALED"&&policyBoundToExecution(b))}}><input name="repair" type="url" required placeholder="Replacement evidence URL"/><button className="outline">Repair failed evidence</button></form>}
 {["REVIEWED","APPEALED"].includes(selected.status)&&selected.verdict!=="REPAIR_REQUIRED"&&<button className="cta full" onClick={()=>void mutate(selected,"finalize",[selected.id],b=>b.status==="FINALIZED"&&policyBoundToExecution(b))}>Finalize after 24h</button>}
 {selected.reason&&<blockquote>{selected.reason}</blockquote>}</article></div>}
 {(phase||error)&&<aside className={`toast ${error||phase==="ERROR"?"bad":""}`} role="status"><b>{error||(phase&&phaseText[phase])}</b>{hash&&<a href={`${EXPLORER}/transactions/${hash}`} target="_blank" rel="noreferrer">View on explorer ↗</a>}<button onClick={()=>{setPhase(null);setError("")}}>×</button></aside>}
 <footer className="site-footer"><b>PATCHARENA</b><span>Bradbury testnet · Contract state is truth.</span></footer></main>
}
